{{ config(materialized='table') }}

select
    jsonb_extract_path_text(_airbyte_data, 'ORG_ID') as org_id,
    jsonb_extract_path_text(_airbyte_data, 'END_DATE') as end_date,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE1') as attribute1,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE2') as attribute2,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE3') as attribute3,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE4') as attribute4,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE5') as attribute5,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE6') as attribute6,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE7') as attribute7,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE8') as attribute8,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE9') as attribute9,
    jsonb_extract_path_text(_airbyte_data, 'CREATED_BY') as created_by,
    jsonb_extract_path_text(_airbyte_data, 'START_DATE') as start_date,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE10') as attribute10,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE11') as attribute11,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE12') as attribute12,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE13') as attribute13,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE14') as attribute14,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE15') as attribute15,
    jsonb_extract_path_text(_airbyte_data, 'PLAN_STATUS') as plan_status,
    jsonb_extract_path_text(_airbyte_data, 'COMP_PLAN_ID') as comp_plan_id,
    jsonb_extract_path_text(_airbyte_data, 'CREATION_DATE') as creation_date,
    jsonb_extract_path_text(_airbyte_data, 'APPROVAL_STATUS') as approval_status,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_DATE1') as attribute_date1,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_DATE2') as attribute_date2,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_DATE3') as attribute_date3,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_DATE4') as attribute_date4,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_DATE5') as attribute_date5,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_DATE6') as attribute_date6,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_DATE7') as attribute_date7,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_DATE8') as attribute_date8,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_DATE9') as attribute_date9,
    jsonb_extract_path_text(_airbyte_data, 'LAST_UPDATED_BY') as last_updated_by,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_DATE10') as attribute_date10,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_DATE11') as attribute_date11,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_DATE12') as attribute_date12,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_DATE13') as attribute_date13,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_DATE14') as attribute_date14,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_DATE15') as attribute_date15,
    jsonb_extract_path_text(_airbyte_data, 'LAST_UPDATE_DATE') as last_update_date,
    jsonb_extract_path_text(_airbyte_data, 'TARGET_INCENTIVE') as target_incentive,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_NUMBER1') as attribute_number1,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_NUMBER2') as attribute_number2,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_NUMBER3') as attribute_number3,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_NUMBER4') as attribute_number4,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_NUMBER5') as attribute_number5,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_NUMBER6') as attribute_number6,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_NUMBER7') as attribute_number7,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_NUMBER8') as attribute_number8,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_NUMBER9') as attribute_number9,
    jsonb_extract_path_text(_airbyte_data, 'LAST_UPDATE_LOGIN') as last_update_login,
    jsonb_extract_path_text(_airbyte_data, 'PLAN_DOC_TEMPLATE') as plan_doc_template,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_CATEGORY') as attribute_category,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_NUMBER10') as attribute_number10,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_NUMBER11') as attribute_number11,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_NUMBER12') as attribute_number12,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_NUMBER13') as attribute_number13,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_NUMBER14') as attribute_number14,
    jsonb_extract_path_text(_airbyte_data, 'ATTRIBUTE_NUMBER15') as attribute_number15,
    jsonb_extract_path_text(_airbyte_data, 'INVALID_REASON_CODE') as invalid_reason_code,
    jsonb_extract_path_text(_airbyte_data, 'INVALID_REASON_TOKENS') as invalid_reason_tokens,
    jsonb_extract_path_text(_airbyte_data, 'OBJECT_VERSION_NUMBER') as object_version_number,
    jsonb_extract_path_text(_airbyte_data, 'ALLOW_ECAT_OVERLAP_FLAG') as allow_ecat_overlap_flag,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    now() as _airbyte_normalized_at
from "pxhgpeza".pxhgpeza._airbyte_raw_cn_comp_plans_all_b as table_alias
-- cn_comp_plans_all_b
where 1 = 1